In [2]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X,y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =0.2)
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [3]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X_train_scaled

array([[ 4.16338558e-01,  7.02708209e-01,  9.42825296e-01,
         1.40624726e+00],
       [-2.85684304e-01, -1.41128863e+00,  1.17795868e-01,
        -1.01568119e-01],
       [ 5.33342369e-01, -1.88106571e+00,  3.92805677e-01,
         1.49734444e-01],
       [-1.68680493e-01,  3.05159359e+00, -1.20225122e+00,
        -9.81127090e-01],
       [-1.45572241e+00,  1.17248528e+00, -1.47726102e+00,
        -1.23242965e+00],
       [ 1.58637666e+00,  2.32931133e-01,  1.27283707e+00,
         7.77990852e-01],
       [ 2.17139571e+00, -7.06623018e-01,  1.65785080e+00,
         1.02929341e+00],
       [-1.22171479e+00, -2.36845942e-01, -1.25725318e+00,
        -1.35808093e+00],
       [ 1.00135761e+00, -2.36845942e-01,  7.22817448e-01,
         6.52339570e-01],
       [-8.70703355e-01,  1.40737382e+00, -1.20225122e+00,
        -9.81127090e-01],
       [ 1.23536523e+00, -1.95740448e-03,  7.77819410e-01,
         1.40624726e+00],
       [-1.68680493e-01, -2.36845942e-01,  2.82801754e-01,
      

In [6]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[ 4.16338558e-01,  7.02708209e-01,  9.42825296e-01,
         1.40624726e+00],
       [-2.85684304e-01, -1.41128863e+00,  1.17795868e-01,
        -1.01568119e-01],
       [ 5.33342369e-01, -1.88106571e+00,  3.92805677e-01,
         1.49734444e-01],
       [-1.68680493e-01,  3.05159359e+00, -1.20225122e+00,
        -9.81127090e-01],
       [-1.45572241e+00,  1.17248528e+00, -1.47726102e+00,
        -1.23242965e+00],
       [ 1.58637666e+00,  2.32931133e-01,  1.27283707e+00,
         7.77990852e-01],
       [ 2.17139571e+00, -7.06623018e-01,  1.65785080e+00,
         1.02929341e+00],
       [-1.22171479e+00, -2.36845942e-01, -1.25725318e+00,
        -1.35808093e+00],
       [ 1.00135761e+00, -2.36845942e-01,  7.22817448e-01,
         6.52339570e-01],
       [-8.70703355e-01,  1.40737382e+00, -1.20225122e+00,
        -9.81127090e-01],
       [ 1.23536523e+00, -1.95740448e-03,  7.77819410e-01,
         1.40624726e+00],
       [-1.68680493e-01, -2.36845942e-01,  2.82801754e-01,
      

In [2]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

data = fetch_openml('car', as_frame=True).frame
data

c:\Users\kerala\OneDrive\Desktop\ml\sck\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [8]:
columns_to_encode = ['lug_boot','safety']

encoder = OrdinalEncoder(
    categories=[
        ['small','med','big'],
        ['low','med','high']
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])
data

buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [9]:
data = fetch_openml('adult',as_frame=True).frame
data

c:\Users\kerala\OneDrive\Desktop\ml\sck\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


age         workclass  fnlwgt  ... hoursperweek  native-country  class
0       2         State-gov   77516  ...            2   United-States  <=50K
1       3  Self-emp-not-inc   83311  ...            0   United-States  <=50K
2       2           Private  215646  ...            2   United-States  <=50K
3       3           Private  234721  ...            2   United-States  <=50K
4       1           Private  338409  ...            2            Cuba  <=50K
...    ..               ...     ...  ...          ...             ...    ...
48837   2           Private  215419  ...            2   United-States  <=50K
48838   4               NaN  321403  ...            2   United-States  <=50K
48839   2           Private  374983  ...            3   United-States  <=50K
48840   2           Private   83891  ...            2   United-States  <=50K
48841   1      Self-emp-inc  182148  ...            3   United-States   >50K

[48842 rows x 15 columns]

In [10]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_values = encoder.fit_transform(data[['occupation']])
new_colms = encoder.get_feature_names_out(['occupation'])

In [13]:
encoded_values


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(48842, 15))

In [14]:
new_colms

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan'], dtype=object)

In [16]:
df_encoded = pd.DataFrame(encoded_values,columns=new_colms, index=data.index)

data_final =pd.concat(
    [data.drop(columns=['occupation']), df_encoded],
    axis=1
)

data_final

age         workclass  ...  occupation_Transport-moving occupation_nan
0       2         State-gov  ...                          0.0            0.0
1       3  Self-emp-not-inc  ...                          0.0            0.0
2       2           Private  ...                          0.0            0.0
3       3           Private  ...                          0.0            0.0
4       1           Private  ...                          0.0            0.0
...    ..               ...  ...                          ...            ...
48837   2           Private  ...                          0.0            0.0
48838   4               NaN  ...                          0.0            1.0
48839   2           Private  ...                          0.0            0.0
48840   2           Private  ...                          0.0            0.0
48841   1      Self-emp-inc  ...                          0.0            0.0

[48842 rows x 29 columns]

In [17]:
from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score,accuracy_score,precision_score,recall_score,f1_score

X,y = load_breast_cancer(return_X_y=True)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [18]:
model = KNeighborsClassifier()
model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [19]:
model.score(X_test_scaled, y_test)

0.9736842105263158

In [26]:
from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,accuracy_score,precision_score,recall_score,f1_score

X,y = load_breast_cancer(return_X_y=True)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

model = KNeighborsClassifier()
model.fit(X_train,y_train)

model.score(X_test, y_test)

0.9473684210526315